name: Artifact testing

on:
  push:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Chckout git repo
        uses: actions/checkout@v2
      
      - name: Archive Something
        uses: actions/upload-artifact@v2
        with:
          name: chicken
          path: file.txt

      - name: Check archived artifacts
        run: |
          let previous=$GITHUB_RUN_ID-1
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Spiroman/Pulling-Actions-Artifact/actions/runs/$previous/artifacts
